import { Octokit } from '@octokit/rest';
import { ResumeData } from '../types/resume';
import { renderTemplate, getTemplateAssets } from './template.service';
import { AppError } from '../middleware/errorHandler';
import path from 'path';
import fs from 'fs';

interface DeployResult {
  repoFullName: string; // owner/repo
  repoUrl: string;      // https://github.com/owner/repo
  pagesUrl: string;     // https://owner.github.io/repo
}

/**
 * Creates a new GitHub repo and pushes the generated portfolio site to it.
 * Enables GitHub Pages on the main branch.
 */
export async function deployToGitHub(
  githubToken: string,
  repoName: string,
  templateId: string,
  data: ResumeData,
): Promise<DeployResult> {
  const octokit = new Octokit({ auth: githubToken });

  // Get authenticated user
  const { data: ghUser } = await octokit.rest.users.getAuthenticated();
  const owner = ghUser.login;

  // Sanitize repo name: lowercase, hyphens only
  const sanitized = repoName
    .toLowerCase()
    .replace(/[^a-z0-9-]/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '');

  // Create repo (public so GitHub Pages works on free tier)
  let repoFullName: string;
  try {
    const { data: repo } = await octokit.rest.repos.createForAuthenticatedUser({
      name: sanitized,
      description: `Portfolio generated by Portfolio Maker`,
      homepage: `https://${owner}.github.io/${sanitized}`,
      auto_init: false,
      private: false,
    });
    repoFullName = repo.full_name;
  } catch (e: any) {
    if (e.status === 422) {
      throw new AppError(
        `A GitHub repo named "${sanitized}" already exists on your account.`,
        409,
      );
    }
    throw e;
  }

  // Build file tree to commit
  const files = await buildFileTree(templateId, data);

  // Create initial commit via Trees API (single round-trip)
  const { data: ref } = await octokit.rest.git.createRef({
    owner,
    repo: sanitized,
    ref: 'refs/heads/main',
    sha: await createInitialCommit(octokit, owner, sanitized, files),
  });

  // Enable GitHub Pages
  try {
    await octokit.rest.repos.createPagesSite({
      owner,
      repo: sanitized,
      source: { branch: 'main', path: '/' },
    });
  } catch {
    // Pages might need a moment; non-fatal
    console.warn('GitHub Pages activation may be pending');
  }

  return {
    repoFullName,
    repoUrl: `https://github.com/${repoFullName}`,
    pagesUrl: `https://${owner}.github.io/${sanitized}`,
  };
}

// ── Helpers ───────────────────────────────────────────────────────────────────

interface FileEntry {
  path: string;
  content: string; // base64 or utf-8 text
  encoding: 'base64' | 'utf-8';
}

async function buildFileTree(
  templateId: string,
  data: ResumeData,
): Promise<FileEntry[]> {
  const files: FileEntry[] = [];

  // Rendered HTML
  const { renderTemplate: render } = await import('./template.service');
  const html = renderTemplate(templateId, data);
  files.push({ path: 'index.html', content: html, encoding: 'utf-8' });

  // data.json
  files.push({
    path: 'data.json',
    content: JSON.stringify(data, null, 2),
    encoding: 'utf-8',
  });

  // Static assets
  const templateDir = path.resolve(__dirname, '../../../templates', templateId);
  const assetPaths = getTemplateAssets(templateId);
  for (const assetPath of assetPaths) {
    const relative = path.relative(templateDir, assetPath).replace(/\\/g, '/');
    const buffer = fs.readFileSync(assetPath);
    files.push({
      path: relative,
      content: Buffer.from(buffer).toString('base64'),
      encoding: 'base64',
    });
  }

  return files;
}

async function createInitialCommit(
  octokit: Octokit,
  owner: string,
  repo: string,
  files: FileEntry[],
): Promise<string> {
  // Create blobs
  const blobs = await Promise.all(
    files.map((f) =>
      octokit.rest.git
        .createBlob({ owner, repo, content: f.content, encoding: f.encoding })
        .then((r) => ({ path: f.path, sha: r.data.sha })),
    ),
  );

  // Create tree
  const { data: tree } = await octokit.rest.git.createTree({
    owner,
    repo,
    tree: blobs.map((b) => ({
      path: b.path,
      mode: '100644',
      type: 'blob',
      sha: b.sha,
    })),
  });

  // Create commit (no parent = initial commit)
  const { data: commit } = await octokit.rest.git.createCommit({
    owner,
    repo,
    message: 'feat: initial portfolio generated by Portfolio Maker',
    tree: tree.sha,
    parents: [],
  });

  return commit.sha;
}
